### PR TITLE
Add PHP CS Fixer to the project

### PR DESCRIPTION
**Pull request by andrewjt71**
Adds PHP CS Fixer to the project as a dev dependency, and run it as part of the travis build.

### CODE REVIEW

**Comment by scheb** [comment]
Hmm, can you explain what's the advantage of running the php-cs-fixer in the Travis job? To my understanding this would only reformat the files locally in the Travis checkout, but overall have no effect.

**Comment by andrewjt71** [comment]
> Hmm, can you explain what's the advantage of running the php-cs-fixer in the Travis job? To my understanding this would only reformat the files locally in the Travis checkout, but overall have no effect.

Hi @scheb , great project by the way, Tombstoning dead code is a new concept to me, and I really like the idea.

Adding it to your Travis build will allow you to fail builds if the detected CS issues have not yet been resolved. The way I'm calling it (note the added flags) will not actually fix the issues, it will just find any issues which have not yet been fixed.

**Comment by andrewjt71** [comment]
Hey @scheb, any thoughts on the above? The purpose is to prevent code from passing CI checks and therefore prevent it from being merged unless it meets the specified coding standards

**Comment by scheb** [comment]
Thought about it, I'd rather integrate PHP code sniffer, e.g. using https://github.com/djoos/Symfony-coding-standard because that one can be connected with the IDE and to highlight violations in the code a gives very specific error messages about what's wrong. Can also be integrated into the build.

**Comment by andrewjt71** [comment]
Hey @scheb, sure, I added PHP CS Fixer to the travis build as that was the code sniffer already being used in the project, but whether you go with PHP CS Fixer or PHP CS is your call 🙂 

It's worth pointing out however that there is PHP CS Fixer support for most IDE's for example [PHPStorm](https://www.jetbrains.com/help/phpstorm/using-php-cs-fixer.html)

All the best!
Andrew T

**Comment by scheb** [comment]
Latest commit is adding a code style. Thanks for your suggestion, gave me the push to add it to the project :)

**Pull request closed without merging**
